import { type Dirent, readdirSync, existsSync, writeFileSync, mkdirSync } from "fs";
import { dirname, join } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));

const localesDir = join(__dirname, "..", "_locales");
const outDir = join(__dirname, "..", "src", "core", "generated");
const outFile = join(outDir, "locales.ts");

const codes = readdirSync(localesDir, { withFileTypes: true })
  .filter((d: Dirent) => d.isDirectory() && existsSync(join(localesDir, d.name, "messages.json")))
  .map((d: Dirent) => d.name)
  .sort();

const codesArrayLiteral = `[\n${codes.map(c => `  ${JSON.stringify(c)},`).join("\n")}\n]`;

mkdirSync(outDir, { recursive: true });
writeFileSync(
  outFile,
  `// Auto-generated by tooling/generate-locales.ts - do not edit\n` +
    `export const LOCALE_CODES = ${codesArrayLiteral} as const;\n` +
    `export type LocaleCode = (typeof LOCALE_CODES)[number];\n`
);

console.log(`Generated ${outFile} with ${codes.length} locales`);
